### ISSUE TITLE
SSH private key in repo

### ISSUE THREAD

**Issue by akx** [ll-O-ll/algos#1]
You seem to have an SSH private key in the repository: https://github.com/ll-O-ll/algos/blob/d1b80018b808b550def0f537118cbc1126ca413e/.ssh/y

While no one probably knows what server(s) it's good for if any, you still shouldn't store private keys (aside from keys used for e.g. tests) in Git repositories, much less public ones.

**Comment by ll-O-ll** [comment]
thanks for letting me know

**Comment by akx** [comment]
Just emptying the files won't help – the data is still there in the previous commit. https://github.com/ll-O-ll/algos/commit/47d5a97f41d46695bba8882e5fbc9c3ecd4f1738#diff-fa571e6a08a3f0c990d7d13a2e004d1c

See https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository
